// Mocks generated by Mockito 5.4.5 from annotations
// in btc_graph/test/unit/services/database_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:btc_graph/entities/bit_coin_rate_graph_data.dart' as _i5;
import 'package:btc_graph/services/database_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set db(_i2.Database? _db) => super.noSuchMethod(
    Invocation.setter(#db, _db),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<_i2.Database> getDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabase, []),
            returnValue: _i4.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.method(#getDatabase, [])),
            ),
          )
          as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> addRate(_i5.BitCoinRateGraphData? rate) =>
      (super.noSuchMethod(
            Invocation.method(#addRate, [rate]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.BitCoinRateGraphData>> getRateList() =>
      (super.noSuchMethod(
            Invocation.method(#getRateList, []),
            returnValue: _i4.Future<List<_i5.BitCoinRateGraphData>>.value(
              <_i5.BitCoinRateGraphData>[],
            ),
          )
          as _i4.Future<List<_i5.BitCoinRateGraphData>>);

  @override
  _i4.Future<int> deleteAllRates() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllRates, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
